# Generated by Django 5.0.6 on 2024-07-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("itau_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyinfo",
            name="facebook",
            field=models.URLField(blank=True, null=True),
        ),
    ]
