# Generated by Django 5.0.6 on 2024-07-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("itau_app", "0002_companyinfo_facebook"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
