# Generated by Django 5.0.6 on 2024-07-07 12:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("itau_app", "0003_blog_likes"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Blog",
            new_name="BlogPost",
        ),
    ]
