# Generated by Django 5.0.6 on 2024-07-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("itau_app", "0004_rename_blog_blogpost"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="blogpost",
            name="subImage2",
            field=models.ImageField(blank=True, null=True, upload_to="blog_images/"),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="tags",
            field=models.ManyToManyField(to="itau_app.tag"),
        ),
    ]
