# Generated by Django 5.0.6 on 2024-07-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("itau_app", "0005_tag_blogpost_subimage2_blogpost_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="tags",
            field=models.ManyToManyField(blank=True, null=True, to="itau_app.tag"),
        ),
    ]
