# Generated by Django 5.0.6 on 2024-07-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("itau_app", "0007_companyinfo_email_alter_blogpost_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testimonial",
            name="image_url",
        ),
        migrations.AddField(
            model_name="testimonial",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="testimonials/"),
        ),
    ]
