# Generated by Django 5.0.6 on 2024-07-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("itau_app", "0008_remove_testimonial_image_url_testimonial_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="client_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="job_title",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
