# Generated by Django 5.0.6 on 2024-07-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("itau_app", "0009_alter_testimonial_client_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimony",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "client_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                ("job_title", models.CharField(blank=True, max_length=25, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="testimonials/"),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Testimonial",
        ),
    ]
