# Generated by Django 5.0.6 on 2024-07-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("itau_app", "0010_testimony_delete_testimonial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OurTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=100)),
                ("facebook", models.URLField(blank=True, null=True)),
                ("twitter", models.URLField(blank=True, null=True)),
                ("linkedin", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
