# Generated by Django 5.0.6 on 2024-07-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("itau_app", "0011_ourteam"),
    ]

    operations = [
        migrations.AddField(
            model_name="ourteam",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="ourTeam_images/"),
        ),
        migrations.AlterField(
            model_name="ourteam",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
