# Generated by Django 5.0.6 on 2024-07-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("itau_app", "0013_career"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyinfo",
            name="location_map",
            field=models.URLField(blank=True, null=True),
        ),
    ]
