# Generated by Django 5.0.6 on 2024-07-12 10:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("itau_app", "0014_companyinfo_location_map"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyinfo",
            name="location_map",
        ),
    ]
