# Generated by Django 5.0.6 on 2024-07-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("itau_app", "0015_remove_companyinfo_location_map"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyinfo",
            name="logo_two",
            field=models.ImageField(default=1, upload_to="logos/"),
            preserve_default=False,
        ),
    ]
