# Generated by Django 5.0.6 on 2024-07-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("itau_app", "0016_companyinfo_logo_two"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyinfo",
            name="logo_two",
            field=models.ImageField(upload_to="logostwo/"),
        ),
    ]
