# Generated by Django 5.0.6 on 2024-07-16 09:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("itau_app", "0017_alter_companyinfo_logo_two"),
    ]

    operations = [
        migrations.AddField(
            model_name="career",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
