# Generated by Django 5.0.6 on 2024-07-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("itau_app", "0018_career_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyinfo",
            name="brochure",
            field=models.FileField(blank=True, null=True, upload_to="brochures/"),
        ),
    ]
