# Generated by Django 5.0.6 on 2024-07-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("itau_app", "0019_companyinfo_brochure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutus",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="about_us_images/"
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="blog_images/"),
        ),
    ]
