# Generated by Django 5.0.6 on 2024-07-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("itau_app", "0021_alter_aboutus_image_alter_blogpost_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutus",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="about_us_images/"
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="blog_images/"),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="subImage",
            field=models.ImageField(blank=True, null=True, upload_to="blog_images/"),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="subImage2",
            field=models.ImageField(blank=True, null=True, upload_to="blog_images/"),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="brochure",
            field=models.FileField(blank=True, null=True, upload_to="brochures/"),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="logo",
            field=models.ImageField(upload_to="logos/"),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="logo_two",
            field=models.ImageField(upload_to="logostwo/"),
        ),
        migrations.AlterField(
            model_name="ourteam",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="ourTeam_images/"),
        ),
        migrations.AlterField(
            model_name="partner",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="partners/"),
        ),
        migrations.AlterField(
            model_name="testimony",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="testimonials/"),
        ),
    ]
