# Generated by Django 5.0.6 on 2024-07-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("itau_app", "0023_aboutus_imageauditors"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyinfo",
            name="pbox",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
