# Generated by Django 5.0.6 on 2024-07-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("itau_app", "0024_companyinfo_pbox"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyinfo",
            name="facebook",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="linkedin",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="pinterest",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="rss",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="twitter",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
